### ISSUE TITLE
Option to include default image when original src fails to load.

### ISSUE THREAD

**Issue by aga5tya** [estrattonbailey/relaze#2]
When there is no image found on the linked src, we could bind onerror to load a default image if provided.? @estrattonbailey Is this by chance already achievable using the lib ? Thanks for making this tiny wonderful lib. 👍

**Comment by estrattonbailey** [comment]
Hey there! Interesting idea, hadn't thought of that.

Could your same functionality be achieved using a pattern like this? I haven't tested this, but should work I think.

```javascript
class Img extends React.Component {
  constructor (props) {
    super(props)
    
    this.state = {
      error: false
    }
  }
  
  render () {
    const props = this.props // clone props so we can mutate
    
    if (this.state.error) {
      props.src = 'path/to/default.jpg'
    }
    
    return <img {...props} onError={e => this.setState({ error: true })}/>
  }
}
```
On the next render after an error (triggered by `setState`) the `relaze` instance should update with the `default.jpg` image and load that.

Open to your thoughts!

**Comment by aga5tya** [comment]
@estrattonbailey, This works for the error image part. Another need is that during ssr i want to have a default blurred base64 image, and then when the viewport kicks in actual image progressively renders.  But relaze component seems to clear off src of child afaik? Thoughts ?

**Comment by estrattonbailey** [comment]
Oh gotcha! Neat idea. I think this may already be possible with an abstraction like the above, albeit in a bit of a roundabout way.

The `...{ props }` above is what is adding the `src` attribute to the `img`, or "clearing it off" in the event there is a `src` already there. So, we *could* just drop the base64 image on their on initial render, load the image using a `img` element in memory, and then update state.

```javascript
class Img extends React.Component {
  constructor (props) {
    super(props)
    
    this.state = {
      src: 'base64img'
    }
  }

  componentDidMount () {
    const img = document.createElement('img')
    const { fullResImage } = this.props

    // when image loads, push actual URL to state
    img.onload = e => this.setState({ src: fullResImage })
    
    // start loading image
    img.src = fullResImage
  }
  
  render () {
    return <img src={this.state.src} />
  }
}
```

Since the image has been cached by your browser by the time it hits Relaze, you shouldn't see a flash. However, you would lose the native progressive rendering of the image file because `onload` will wait for all data to come through.

Would that work for your case?

The alternative would probably be to include initial value options for the `src`, `srcSet`, and `retina` options on Relaze instances. That would work too but I'd ideally avoid it just to keep the API simple.

Given your custom solution I'd also recommend just using an *in-viewport* library of some kind an implementing a custom loading mechanism like my example above. This library, [visibl](https://github.com/estrattonbailey/visibl), is the same scroll logic as Relaze, but only does in-viewport watching. There are certainly more robust implementations out there as well.
